Fix unbound_rhs (#78)
This patch fixes errors like this

julia> @floop for x in 1:2
@init p = []
end
ERROR: LoadError: ArgumentError: reducing over an empty collection is not allowed

which is caused by `unbound_rhs(:([]))`.